version: '2'
services:
  api_repl:
    build:
      context: .
      dockerfile: api/Dockerfile-repl
    volumes:
     - .:/fenle
    entrypoint: ../mysql/wait-for-mysql.py python ipython-entrypoint.py
    depends_on:
     - mysql
     - redis
  sit_repl:
    build:
      context: .
      dockerfile: sit/Dockerfile-repl
    volumes:
     - .:/fenle
    entrypoint: ../mysql/wait-for-mysql.py python ipython-entrypoint.py
    depends_on:
     - mysql
     - redis
  tools:
    build:
      context: .
      dockerfile: tools/Dockerfile
    volumes:
     - .:/fenle
    depends_on:
     - mysql
