version: '2'
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
     - .:/fenle
    ports:
     - "3032:3031"
    depends_on:
     - mysql
     - redis
  callback_url:
    build:
      context: .
      dockerfile: callback_url/Dockerfile
    volumes:
     - .:/fenle
    ports:
     - "3033:3031"
    depends_on:
     - mysql
  wx_prog:
    build:
      context: .
      dockerfile: wx_prog/Dockerfile
    environment:
      FENLE_SETTINGS: local
    volumes:
     - .:/fenle
    ports:
     - "3034:3031"
    depends_on:
     - mysql
     - redis
  sit:
    build:
      context: .
      dockerfile: sit/Dockerfile
    volumes:
     - .:/fenle
    ports:
     - "3035:3031"
    depends_on:
     - mysql_sit
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
    volumes:
     - "db-data:/var/lib/mysql"
  mysql_sit:
    build:
      context: .
      dockerfile: sit/Dockerfile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fenle_fenqi_db
      - MYSQL_ROOT_HOST=%
      - LANG=en_US.UTF-8
  redis:
    image: redis

volumes:
    db-data:
