version: '2'
services:
  mysql:
    build:
      context: ..
      dockerfile: mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fenle_fenqi_db
      - MYSQL_ROOT_HOST=%
      - LANG=en_US.UTF-8
