CREATE TABLE merchant_info (
        spid varchar(16) NOT NULL UNIQUE,
        name varchar(64),
        uid integer UNIQUE,
        fee_contract_no integer,
        contract_no varchar(64),
        corporation_name varchar(64),
        corporation_credid varchar(64),
        licence varchar(64),
        corp_address varchar(128),
        mobile varchar(11),
        tel varchar(65),
        user_id varchar(65),
        modify_time timestamp,
        status smallint,
        mer_key varchar(64),
        state smallint DEFAULT 1,
        list_state smallint,
        withdraw_type smallint,
        memo varchar(128),
        ip inet
        );

CREATE TABLE spid_contract (
        id bigserial PRIMARY KEY,
        contract_id varchar(32) NOT NULL UNIQUE,
        spid varchar(16) NOT NULL,
        platform_spid varchar(16),
        settle_scene int,
        start_date date,
        end_date date,
        trans_cur_type int,
        setting_cur_type int,
        sp_bank_acc varchar(32),
        sp_bank_acc_name varchar(64),
        sp_bank_name varchar(64),
        sp_bank_branch varchar(64),
        fee_rate numeric,
        contract_state smallint,
        protocol_state smallint,
        create_id varchar(64),
        create_ip inet,
        create_time timestamp,
        create_memo varchar(128),
        modify_id varchar(64),
        modify_ip inet,
        modify_time timestamp,
        modify_memo varchar(128),
        check_id varchar(64),
        check_ip inet,
        check_time timestamp,
        check_memo varchar(128),
        memo varchar(128),
        last_time timestamp,
        operate_state smallint,
        operate_id bigint
        );

CREATE TABLE merchant_login_user (
        uid integer NOT NULL,
        truename varchar(64),
        dept_name varchar(64),
        passwd varchar(33),
        sex smallint,
        login_id varchar(65) NOT NULL UNIQUE,
        mobile varchar(11),
        email varchar(65),
        memo varchar(128),
        state smallint,
        last_time timestamp,
        last_ip inet,
        spid varchar(16) NOT NULL,
        crt_id int,
        op_type smallint,
        lstate smallint,
        sign bit varying(32)
        );

CREATE TABLE sp_user (
        uid integer NOT NULL,
        curtype smallint NOT NULL DEFAULT 1,
        spid varchar(16) NOT NULL,
        truename varchar(64),
        company_name varchar(64),
        balance bigint NOT NULL DEFAULT 0,
        con_settle bigint NOT NULL DEFAULT 0,
        yday_balance bigint NOT NULL DEFAULT 0,
        min_balance bigint NOT NULL DEFAULT 0,
        save_time timestamp,
        fetch_time timestamp,
        change_ip inet,
        state smallint,
        memo varchar(128),
        modify_time timestamp,
        create_time timestamp,
        balance_time timestamp,
        UNIQUE (uid, curtype)
        );

CREATE TABLE sp_bankroll_list (
        bkid bigserial PRIMARY KEY,
        list_id varchar(32),
        spid varchar(16),
        uid integer NOT NULL,
        truename varchar(64),
        type smallint,
        subject integer,
        from_id varchar(64),
        from_name varchar(64),
        balance bigint NOT NULL DEFAULT 0,
        con bigint NOT NULL DEFAULT 0,
        pay_num bigint NOT NULL DEFAULT 0,
        sp_num bigint NOT NULL DEFAULT 0,
        con_num NOT NULL DEFAULT 0,
        bank_type smallint,
        curtype smallint,
        prove char(32),
        memo varchar(128),
        action_type smallint,
        modify_time_acc timestamp,
        modify_time timestamp,
        create_time timestamp,
        rollback_time timestamp,
        explain varchar(128),
        list_sign smallint
        );

CREATE TABLE bank (
        bank_id varchar(32),
        acc_type integer,
        state smallint,
        bank_name varchar(32),
        bank_type smallint,
        truename varchar(64),
        area varchar(16),
        city varchar(16),
        curtype smallint,
        balance bigint NOT NULL DEFAULT 0,
        yday_balance bigint NOT NULL DEFAULT 0,
        create_time timestamp,
        ip inet,
        memo varchar(128),
        modify_time timestamp
        );

CREATE TABLE trans_list (
        transaction_id varchar(32) PRIMARY KEY,
        coding varchar(32),
        spid varchar(16),
        bank_list varchar(32),
        bank_roll varchar(32),
        request_sn varchar(32),
        uname varchar(64),
        bank_type integer,
        bank_name varchar(64),
        bank_area varchar(16),
        bank_city varchar(16),
        mobile varchar(32),
        bankacc_no varchar(32),
        bankacc_type smallint,
        bankacc_attr smallint,
        pin_code varchar(32),
        bank_valicode varchar(32),
        valid_period varchar(8),
        iterface_type smallint,
        rsp_time varchar(16),
        curtype smallint,
        credit_type smallint,
        credit_id varchar(64),
        bank_channel varchar(16),
        pay_type smallint,
        trade_type smallint,
        memo varchar(128),
        riskctrl_mask int NOT NULL DEFAULT 0,
        service_mask int NOT NULL DEFAULT 0,
        payflow_mask int NOT NULL DEFAULT 0,
        direct smallint,
        amount bigint NOT NULL DEFAULT 0,
        paynum bigint NOT NULL DEFAULT 0,
        fee bigint NOT NULL DEFAULT 0,
        bank_fee bigint NOT NULL DEFAULT 0,
        token varchar(32),
        valid_cnt int,
        state smallint,
        lstate smallint,
        adjust_flag smallint,
        create_time timestamp,
        modify_time timestamp,
        bankacc_time timestamp,
        pay_time timestamp,
        future_time timestamp,
        settle_time timestamp,
        last_retcode varchar(16),
        last_retinfo varchar(64),
        explain varchar(256),
        client_ip inet,
        modify_ip inet,
        refund_id varchar(32),
        extend_spinfo varchar(256),
        serial_id varchar(32),
        UNIQUE (bank_list, bank_type)
        );

CREATE TABLE lf_bankroll_list (
        list_id varchar(32),
        spid varchar(16),
        account_id varchar(32),
        account_type smallint,
        type smallint,
        thirdpart smallint,
        pay_num bigint
        amount bigint,
        income_num bigint,
        state smallint,
        sign smallint,
        bank_list varchar(32),
        bank_backid varchar(32),
        bank_type smallint,
        curtype smallint,
        aid varchar(65),
        aname varchar(64),
        prove varchar(32),
        ip inet,
        memo varchar(128),
        pay_front_time timestamp,
        pay_time timestamp,
        pay_time_acc timestamp,
        bank_time timestamp,
        modify_time timestamp,
        create_time timestamp,
        refund_time timestamp,
        msg_no varchar(64),
        save_type smallint,
        PRIMARY KEY(list_id, bank_list, bank_type)
        );

CREATE TABLE lf_pay_list (
        tde_id bigserial PRIMARY KEY,
        list_id varchar(32),
        draw_id varchar(32),
        sp_operator varchar(65),
        spid varchar(16),
        fl_pay_type integer,
        business_type integer,
        type smallint,
        subject integer,
        num bigint NOT NULL DEFAULT 0,
        charge bigint NOT NULL DEFAULT 0,
        charge_payer smallint,
        charge_recv_uid int,
        state smallint,
        sign smallint,
        bank_list varchar(32),
        bank_acc varchar(32),
        bank_type smallint,
        curtype smallint,
        my_bankaccid varchar(32),
        aname varchar(64),
        abank_type smallint,
        abankid varchar(32),
        prove char(32),
        ip inet,
        memo varchar(128),
        bank_memo varchar(128),
        result varchar(255),
        refund_ticket_flag smallint,
        refund_ticket_list varchar(32),
        pay_front_time timestamp,
        pay_time timestamp,
        modify_time timestamp,
        bank_name varchar(64),
        area varchar(16),
        city varchar(16),
        acc_name varchar(64),
        user_type smallint
        );
